name: Archive to Wayback Machine

on:
  deployment_status:

jobs:
  archive:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Save my site
        uses: JamieMagee/wayback@v2
        
